### ISSUE TITLE
+3124851948 is rejected, but 3124851948 is not

### ISSUE THREAD

**Issue by darrennix** [waratuman/phone_validator#1]
If initial pattern correction fails, should strip + and re-attempt pattern correction.

**Comment by waratuman** [comment]
https://github.com/floere/phony is actually used for verification at the moment. It's an international library and think it would be difficult to add this verification.

The problem with stripping of the + means you are defaulting to whichever country the phone number format fits at random, and the + is used for international dialing, so it's assumed that someone is trying to reach the country with the '+31' calling code http://en.wikipedia.org/wiki/List_of_country_calling_codes.

**Comment by darrennix** [comment]
Makes sense
